version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: pyscraper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    environment:
      DB_NAME: pyscraper
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app

volumes:
  db-data:


